#!/usr/bin/env bash
# a script that installs and redirects /redirect_me on nginx server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -e "52i \\\t\tadd_header X-Served-By '\$hostname';" -i /etc/nginx/sites-available/default;
sudo service nginx restart
sudo service nginx start